import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/componants/Header";
import Footer from "@/componants/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=" bg-white">
      <div className="flex h-screen flex-col justify-between font-sans">
        <Header/>
        <main className="mb-auto">{children}</main>
        <Footer/>
        </div>
        </body>
    </html>
  );
}
